Repository FESP-TEAM-1/final-project, pull requests merged in 2023-11, with the labels that each got.

#4 feat/page-main: 메인 페이지 마크업 및 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/layout/Header.tsx
  src/components/main/Card.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/Main/Card.module.css
  src/styles/Main/MainPage.module.css
  src/styles/layout/Header.module.css
  src/types/mainItem.ts
  src/utils/getElapsedTime.ts
Labels: 🎨 디자인, 🛠️ 기능개발, 👥 공동작업, ⚙️ 개발환경, ♻️ 리팩토링

#9 feat/skeleton : 메인, 상세 페이지 스켈레톤 UI 작업
  package-lock.json
  package.json
  src/components/detail/DetailSkeleton.tsx
  src/components/main/MainSkeleton.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
Labels: 🎨 디자인, 👥 공동작업, ♻️ 리팩토링

#13 feat/page detail comment : 댓글 기능 추가
  package-lock.json
  package.json
  src/api/comment/deleteCommentAPI.ts
  src/api/comment/getCommentAPI.ts
  src/api/comment/index.ts
  src/api/comment/insertCommentAPI.ts
  src/components/detail/Comment.tsx
  src/components/detail/CommentForm.tsx
  src/components/detail/DetailSkeleton.tsx
  src/components/detail/RelatedCard.tsx
  src/components/detail/Video.tsx
  src/components/main/MainSkeleton.tsx
  src/pages/DetailPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/detail/Comment.module.css
  src/styles/detail/CommentForm.module.css
  src/styles/detail/DetailPage.module.css
  src/styles/detail/RelatedCard.module.css
  src/styles/detail/Video.module.css
  src/supabase/videoComment.ts
  src/types/commentItem.ts
  src/types/supabaseComment.ts
Labels: 🎨 디자인, 🛠️ 기능개발, ⚙️ 개발환경

#11 feat/theme: 테마 기능 추가
  src/Root.tsx
  src/components/detail/DetailSkeleton.tsx
  src/components/layout/Header.tsx
  src/components/main/MainSkeleton.tsx
  src/stores/useThemeStore.ts
  src/styles/GlobalStyle.ts
  src/styles/Main/Card.module.css
  src/styles/detail/RelatedCard.module.css
  src/styles/detail/Video.module.css
  src/styles/layout/Header.module.css
Labels: 🎨 디자인, 🛠️ 기능개발, 👥 공동작업

#14 feat/page search: 검색 페이지 마크업 및 기능 구현
  src/Router.tsx
  src/components/detail/Comment.tsx
  src/components/layout/Header.tsx
  src/components/search/SearchCard.tsx
  src/components/search/SearchSkeleton.tsx
  src/pages/SearchPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/Main/MainPage.module.css
  src/styles/detail/Comment.module.css
  src/styles/layout/Header.module.css
  src/styles/search/SearchCard.module.css
  src/styles/search/SearchPage.module.css
Labels: 🎨 디자인, 🛠️ 기능개발, 👥 공동작업

#15 feat/animation : Card 컴포넌트 호버 시 영상 자동 재생 애니메이션 기능 추가
  src/components/main/Card.tsx
  src/styles/Main/Card.module.css
  src/styles/Main/MainPage.module.css
Labels: 🎨 디자인, 🛠️ 기능개발

#16 feat/animation : Main 페이지 반응형에서 hover 자동 재생 기능 삭제 및 Detail, Search 페이지 hover 영상 자동 재생 기능 추가
  src/components/detail/RelatedCard.tsx
  src/components/main/Card.tsx
  src/components/search/SearchCard.tsx
  src/styles/Main/Card.module.css
  src/styles/search/SearchCard.module.css
Labels: 🎨 디자인, 🛠️ 기능개발, 🐞 버그

#17 feat/theme : Detail 페이지 theme css 색상 변수 추가 및 적용
  src/components/detail/Comment.tsx
  src/styles/GlobalStyle.ts
  src/styles/detail/Comment.module.css
  src/styles/detail/CommentForm.module.css
  src/styles/main/Card.module.css
  src/styles/main/MainPage.module.css
Labels: 🎨 디자인

#18 feat/page detail: 상세 페이지 댓글 스켈레톤 추가
  src/components/detail/DetailSkeleton.tsx
Labels: 🎨 디자인

#19 feat/page detail: Detail 페이지 컴포넌트화 작업
  src/components/detail/CommentSection.tsx
  src/components/detail/DetailSkeleton.tsx
  src/components/detail/RelatedSection.tsx
  src/components/detail/VideoSection.tsx
  src/pages/DetailPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/detail/DetailPage.module.css
  src/styles/detail/RelatedSection.module.css
  src/styles/detail/Video.module.css
Labels: 🎨 디자인, 👥 공동작업, ♻️ 리팩토링

#20 refactor/fetching : API 모듈화 및 React-Query fetching, custom hook 생성
  src/api/comment/deleteCommentAPI.ts
  src/api/comment/getCommentAPI.ts
  src/api/comment/insertCommentAPI.ts
  src/api/detail/deleteCommentAPI.ts
  src/api/detail/getChannelDataAPI.ts
  src/api/detail/getCommentAPI.ts
  src/api/detail/getVideoAPI.ts
  src/api/detail/index.ts
  src/api/detail/insertCommentAPI.ts
  src/api/main/getVideoListAPI.ts
  src/api/main/index.ts
  src/api/search/getSearchVideoListAPI.ts
  src/api/search/index.ts
  src/components/detail/Comment.tsx
  src/components/detail/CommentForm.tsx
  src/components/detail/CommentSection.tsx
  src/components/detail/RelatedCard.tsx
  src/components/detail/RelatedSection.tsx
  src/components/detail/Video.tsx
  src/components/detail/VideoSection.tsx
  src/components/main/Card.tsx
  src/components/search/SearchCard.tsx
  src/hooks/useHandleHover.tsx
  src/hooks/useHandleResizeHeight.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/stores/useItemStore.ts
  src/styles/detail/Comment.module.css
Labels: 👥 공동작업, ♻️ 리팩토링

#22 feat/infinite-scroll : 유튜브 API 연결 및 무한 스크롤 구현
  .gitignore
  package-lock.json
  package.json
  public/videos/popular.json
  public/videos/searchByChannels/search-by-channel-id-UC1x03ziDHPct2xTikLyfMDA.json
  public/videos/searchByChannels/search-by-channel-id-UC37fRkl_iIjDAr9pf0FFzGA.json
  public/videos/searchByChannels/search-by-channel-id-UC4ZA57iJrf73bJlApKFeLRw.json
  public/videos/searchByChannels/search-by-channel-id-UC98Dpw8CHzoPuEYbL9SnXWQ.json
  public/videos/searchByChannels/search-by-channel-id-UCAyvCxdhYV-Zg7PSGZJoQ2A.json
  public/videos/searchByChannels/search-by-channel-id-UCDNvRZRgvkBTUkQzFoT_8rA.json
  public/videos/searchByChannels/search-by-channel-id-UCI2T1_bAtgnKKzfhw3Qib9w.json
  public/videos/searchByChannels/search-by-channel-id-UCK5fO9Q2gitao0M5yQvPnvw.json
  public/videos/searchByChannels/search-by-channel-id-UCLItMtuFPIZ-Q0m_oOVwB2Q.json
  public/videos/searchByChannels/search-by-channel-id-UCQ2O-iftmnlfrBuNsUUTofQ.json
  public/videos/searchByChannels/search-by-channel-id-UCSknObj2PGGK6KCkTyc5Kkw.json
  public/videos/searchByChannels/search-by-channel-id-UCTQVIXvcHrR9jYoJ6qaBAow.json
  public/videos/searchByChannels/search-by-channel-id-UCUQVGXF4U-PupGCPdIRX4Qw.json
  public/videos/searchByChannels/search-by-channel-id-UCUyfkq9e9ZfPzxOW5WQ9rzQ.json
  public/videos/searchByChannels/search-by-channel-id-UCWYzc_p0GgfCepIWDHGFmEg.json
  public/videos/searchByChannels/search-by-channel-id-UCXEKwWflysXu312NmIP_dlw.json
  public/videos/searchByChannels/search-by-channel-id-UCbD8EppRX3ZwJSou-TVo90A.json
  public/videos/searchByChannels/search-by-channel-id-UCepUWUpH45hRTi-QePdq1Bg.json
  public/videos/searchByChannels/search-by-channel-id-UCmJEpV4hLzGWLU5rrdOHMhQ.json
  public/videos/searchByChannels/search-by-channel-id-UCnBht7BrOx-A328KFXgysqQ.json
  public/videos/searchByChannels/search-by-channel-id-UCnCEKlzi52Yzj2JdBFhKVEA.json
  public/videos/searchByChannels/search-by-channel-id-UCtCiO5t2voB14CmZKTkIzPQ.json
  public/videos/searchByChannels/search-by-channel-id-UCw-kXdzxMdMdLNI0ZlFFbmA.json
  public/videos/searchByChannels/search-by-channel-id-UCx6jsZ02B4K3SECUrkgPyzg.json
  src/api/detail/getChannelDataAPI.ts
  src/api/detail/getCommentAPI.ts
  src/api/detail/getVideoAPI.ts
  src/api/main/getVideoListAPI.ts
  src/api/search/getSearchVideoListAPI.ts
  src/components/detail/CommentSection.tsx
  src/components/detail/RelatedSection.tsx
  src/components/layout/Header.tsx
  src/hooks/useHandleScroll.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/styles/detail/CommentSection.module.css
Labels: 🛠️ 기능개발, 👥 공동작업

#23 feat/page-detail : Detail 페이지 스켈레톤 영역 분리 및 영상 클릭 시 이동 기능 추가
  src/components/detail/CommentSection.tsx
  src/components/detail/DetailSkeleton.tsx
  src/components/detail/RelatedCard.tsx
  src/components/detail/Video.tsx
  src/components/detail/skeleton/Comment.tsx
  src/components/detail/skeleton/RelatedVideo.tsx
  src/components/detail/skeleton/Video.tsx
  src/components/detail/skeleton/index.ts
  src/components/main/Card.tsx
  src/components/search/SearchCard.tsx
  src/styles/GlobalStyle.ts
Labels: 🎨 디자인, 🛠️ 기능개발, 👥 공동작업

#25 feat/image-lazy-loading : 이미지 lazy-loading 기능 추가
  src/components/detail/RelatedCard.tsx
  src/components/main/Card.tsx
  src/components/search/SearchCard.tsx
  src/hooks/useImgLazyLoading.tsx
Labels: 🛠️ 기능개발, 👥 공동작업

#27 fix/card-scale : hover 시 영상 짤리는 것 및 페이지 이탈 시 축소 되지 않는 버그 수정
  src/components/detail/RelatedCard.tsx
  src/components/main/Card.tsx
  src/hooks/useHandleHover.tsx
  src/hooks/useHandleMainHover.tsx
  src/pages/SearchPage.tsx
  src/styles/detail/DetailPage.module.css
  src/styles/detail/RelatedCard.module.css
  src/styles/main/MainPage.module.css
  src/styles/search/SearchCard.module.css
  src/styles/search/SearchPage.module.css
Labels: 🎨 디자인, 🐞 버그

#30 refactor/code : 클린 코드 적용
  src/api/fakeYoutubeClient.ts
  src/components/detail/Comment.tsx
  src/components/detail/RelatedCard.tsx
  src/components/main/Card.tsx
  src/components/search/SearchCard.tsx
  src/hooks/useHandleHover.tsx
  src/hooks/useHandleMainHover.tsx
  src/pages/SearchPage.tsx
  src/stores/useYoutubeApiStore.ts
  src/types/popularVideo.ts
  src/utils/setDecodeHTMLEntities.ts
Labels: 👥 공동작업, ♻️ 리팩토링

#32 🚑 HotFix: 버그 긴급 수정
  src/api/fakeYoutubeClient.ts
  src/api/youtube.ts
  src/api/youtubeClient.ts
  src/components/detail/RelatedCard.tsx
  src/components/detail/RelatedSection.tsx
  src/components/detail/Video.tsx
  src/components/layout/Header.tsx
  src/components/search/SearchCard.tsx
  src/pages/ErrorPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/detail/RelatedCard.module.css
  src/types/mainItem.ts
  src/types/popularVideo.ts
  src/types/relatedVideo.ts
Labels: 🐞 버그

#33 hotFix: 로고 이미지 경로 수정
  src/components/layout/Header.tsx
  src/pages/ErrorPage.tsx
Labels: 👥 공동작업, 🐞 버그
